<?php
return [
    "index"=>"主页模板",
    "head"=>" 公用头部模板",
    "footer"=>"公用底部模板",
    "taglist"=>"标签首页模板",
    "search"=>"普通搜索模板",
    "sitemap"=>"网站地图模板",
    "list_article"=>"文章集列表模板",
    "list_image"=>"图片集列表模板",
    "list_product"=>"产品列表模板",
    "list_video"=>"视频列表模板",
    "list_ask"=>"问题列表模板",
    "view_article"=>"文章内容页模板",
    "view_image"=>"图片内容页模板",
    "view_product"=>"产品内容页模板",
    "view_video"=>"视频内容页模板",
    "view_ask"=>"问题内容页模板",
    "index_single"=>"单页面模板",
    "index_m"=>"手机端主页模板",
    "head_m"=>" 手机端公用头部模板",
    "footer_m"=>"手机端公用底部模板",
    "taglist_m"=>"手机端标签首页模板",
    "search_m"=>"手机端普通搜索模板",
    "sitemap_m"=>"手机端网站地图模板",
    "list_article_m"=>"手机端文章集列表模板",
    "list_image_m"=>"手机端图片集列表模板",
    "list_product_m"=>"手机端产品列表模板",
    "list_video_m"=>"手机端视频列表模板",
    "list_ask_m"=>"手机端问题列表模板",
    "view_article_m"=>"手机端文章内容页模板",
    "view_image_m"=>"手机端图片内容页模板",
    "view_product_m"=>"手机端产品内容页模板",
    "view_video_m"=>"手机端视频内容页模板",
    "view_ask_m"=>"手机端问题内容页模板",
    "index_single_m"=>"手机端单页面模板"
];